<a href="https://colab.research.google.com/github/sowmyarajesh/ML_TensorFlow/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
import numpy as np

### Ranks


In [3]:
# Rank 0 = Scalars => simple variables
person = tf.Variable("nameofP",tf.string)
score =tf.Variable(20, tf.int16)
float_score =tf.Variable(12.4,tf.float64)
complex_num = tf.Variable(2.1+3j, tf.complex64)


In [4]:
# Rank 1 => vectors
scores = tf.Variable([2,3,5,1],tf.int16)
floatRank = tf.Variable([2.4,1.45,8.9,0.0], tf.float32)


In [14]:
# higher rank = n-dimensional arrays
mtx = tf.Variable([[1,2,3],[3,4,5],[2,3,4],[4,2,5]],tf.int32)

In [15]:
tf.rank(mtx)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
tf.shape(mtx)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

In [17]:
tf.reshape(mtx, [3,4]),

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[1, 2, 3, 3],
        [4, 5, 2, 3],
        [4, 4, 2, 5]], dtype=int32)>,)

WE can use slicing and dicing rules from numpy

In [20]:
npMtx = np.array([[1,2,3],[3,4,5],[2,3,4],[4,2,5]])
npMtx[1][1]

4

## sessions

In [25]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
x = tf.constant([1,2,3])
y = tf.constant(3)
c =x*y

with tf.compat.v1.Session() as s:
  s.run(c)

In [28]:
sess = tf.compat.v1.InteractiveSession()
c.eval()
sess.close()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1768: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
